//! Generates the transparent-vs-learned-baseline comparison table for
//! `docs/model-comparison.md`.
//!
//! Run with:
//! ```text
//! cargo run --release -p plugin-agent-detect --example model_comparison
//! ```
//!
//! Trains the logistic-regression baseline ([`plugin_agent_detect::baseline`]) on
//! naive synthetic data, then scores it head-to-head against the transparent
//! [`Model`](plugin_agent_detect::model::Model) on a shared, disjoint held-out test
//! set at each evasion budget — both via the identical [`roc_auc`] estimator. Every
//! number is produced through the *real* feature pipeline and is deterministic given
//! the seed.
//!
//! **Read with the caveat:** the learned baseline trains on the same generator it is
//! tested against and can overfit the generator's idiosyncrasies, so this is a
//! cross-check on competitiveness, not a claim of field accuracy. See the module
//! docs in `baseline.rs` and the discussion in `docs/model-comparison.md`.

use plugin_agent_detect::eval::{compare_models_across_evasion, ModelComparison};

const N_TRAIN_PER_CLASS: usize = 600;
const N_TEST_PER_CLASS: usize = 400;
const SEEDS: &[u64] = &[1, 2, 3, 4, 5];
const BUDGETS: &[f64] = &[0.0, 0.25, 0.5, 0.75, 1.0];

fn main() {
    // Average each cell across seeds for stability (deterministic given SEEDS).
    let mut acc: Vec<(f64, f64, f64)> = BUDGETS.iter().map(|&e| (e, 0.0, 0.0)).collect();
    for &seed in SEEDS {
        let rows: Vec<ModelComparison> =
            compare_models_across_evasion(N_TRAIN_PER_CLASS, N_TEST_PER_CLASS, seed, BUDGETS);
        for (a, r) in acc.iter_mut().zip(rows.iter()) {
            a.1 += r.transparent_auc;
            a.2 += r.learned_auc;
        }
    }
    let n = SEEDS.len() as f64;

    println!("# Transparent vs. learned-baseline ROC-AUC (synthetic, reproducible)\n");
    println!(
        "> Generated by `cargo run --release -p plugin-agent-detect --example model_comparison`.\n\
         > Each cell averages {} seeds {:?}; train = {} agent + {} human naive sessions,\n\
         > held-out test = {} agent + {} human sessions per budget. Both models are scored\n\
         > on the *same* held-out rows with the *same* ROC-AUC estimator.\n",
        SEEDS.len(),
        SEEDS,
        N_TRAIN_PER_CLASS,
        N_TRAIN_PER_CLASS,
        N_TEST_PER_CLASS,
        N_TEST_PER_CLASS
    );
    println!("| evasion e | transparent AUC | learned-baseline AUC | Δ (transparent − learned) |");
    println!("|----------:|----------------:|---------------------:|--------------------------:|");
    for (e, t, l) in &acc {
        let (t, l) = (t / n, l / n);
        println!("| {:.2} | {:.4} | {:.4} | {:+.4} |", e, t, l, t - l);
    }
}
